#!/usr/bin/env bash

source ${HOME}/.bash_profile

BASEDIR=$(dirname "$(dirname "$0")")
PYTHONDIR=${BASEDIR}/Resources

export PYTHONPATH=${PYTHONDIR}:$PYTHONPATH

${BASEDIR}/Resources/apss_pipeline_gui.py
